-- Update data types for the patients table based on the suggestions

-- 1. Name: text -> varchar(255)
ALTER TABLE patients 
ALTER COLUMN name TYPE varchar(255);

-- 2. Pekerjaan: text -> varchar(100)
ALTER TABLE patients 
ALTER COLUMN pekerjaan TYPE varchar(100);

-- 3. Phone: text -> varchar(20)
ALTER TABLE patients 
ALTER COLUMN phone TYPE varchar(20);

-- 4. Gender: text -> varchar(10)
ALTER TABLE patients 
ALTER COLUMN gender TYPE varchar(10);

-- 5. Umur: int4 -> smallint
ALTER TABLE patients 
ALTER COLUMN umur TYPE smallint;

-- Note for ID: 
-- 'int8' is already the same as 'bigint'. 
-- If you need it to be auto-incrementing (bigserial), it should likely already be set as IDENTITY.
-- If not, you can run: 
-- ALTER TABLE patients ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY;
