-- 1. Create transaction_details table
CREATE TABLE transaction_details (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    transaction_id BIGINT REFERENCES transactions(id) ON DELETE CASCADE,
    package_id SMALLINT REFERENCES packages(id),
    price NUMERIC NOT NULL
);

-- 2. Migrate existing data (Optional but recommended to not lose data)
-- Assuming 'amount' in transactions was the price of the package
INSERT INTO transaction_details (transaction_id, package_id, price)
SELECT id, package_id, amount
FROM transactions
WHERE package_id IS NOT NULL;

-- 3. Modify transactions table structure
ALTER TABLE transactions
    DROP COLUMN IF EXISTS patient_name,
    DROP COLUMN IF EXISTS package_id,
    DROP COLUMN IF EXISTS package_name,
    DROP COLUMN IF EXISTS user_name,
    DROP COLUMN IF EXISTS diagnosis_name;

-- Rename amount to total_amount (Must be separate statement)
ALTER TABLE transactions RENAME COLUMN amount TO total_amount;

-- Ensure columns are correct types/FKs
ALTER TABLE transactions ALTER COLUMN id TYPE bigint;
ALTER TABLE transactions ALTER COLUMN date TYPE date;
ALTER TABLE transactions ALTER COLUMN patient_id TYPE bigint;
ALTER TABLE transactions ALTER COLUMN user_id TYPE uuid;
ALTER TABLE transactions ALTER COLUMN diagnosis_id TYPE bigint;
ALTER TABLE transactions ALTER COLUMN created_at TYPE timestamptz USING created_at AT TIME ZONE 'UTC';
